server:
  port: ${PORT}

spring:
  datasource:
    url: jdbc:mysql://${URL}/${DB_NAME}?useSSL=false
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt-set-uri: https://authdesa.duckdns.org:22002/realms/DESA2023/protocol/openid-connect/certs
        jwt:
          issuer-uri: https://authdesa.duckdns.org:22002/realms/DESA2023

securitySchemes:
  keycloak:
    type: oauth2
    flows:
      implicit:
        authorizationUrl: https://authdesa.duckdns.org:22002/realms/DESA2023/protocol/openid-connect/certs